In [3]:
from os import listdir
import numpy as np
import tensorflow as tf
from PIL import Image

In [4]:
files = listdir('Dataset/')

In [5]:
n_files = len(files)
X = np.zeros((n_files,64,64,3))
Y_age_gender = np.zeros((n_files,2))

In [15]:
for i in range(n_files):
#     img = Image.open('Dataset/' + files[i]).resize((64,64)).convert("L")
    X[i] = np.array(Image.open('Dataset/' + files[i]).resize((64,64)))
    split = files[i].split('_')
    Y_age_gender[i] = np.asarray([int(split[0]), int(split[1])])

In [7]:
print(X)

[[[[209. 200. 195.]
   [203. 194. 187.]
   [170. 161. 153.]
   ...
   [ 95. 100. 101.]
   [ 92.  97. 100.]
   [ 93.  96. 106.]]

  [[204. 195. 190.]
   [196. 187. 180.]
   [153. 144. 136.]
   ...
   [ 97. 101. 101.]
   [ 95.  98. 103.]
   [ 95.  97. 108.]]

  [[213. 204. 199.]
   [181. 172. 166.]
   [156. 147. 139.]
   ...
   [104. 106. 107.]
   [ 99. 100. 105.]
   [ 97.  97. 107.]]

  ...

  [[243. 242. 248.]
   [239. 238. 244.]
   [236. 235. 241.]
   ...
   [ 98.  97. 103.]
   [ 97.  96. 102.]
   [ 96.  95. 101.]]

  [[238. 237. 243.]
   [235. 234. 240.]
   [230. 229. 235.]
   ...
   [ 97.  96. 102.]
   [ 96.  95. 101.]
   [ 95.  94. 100.]]

  [[235. 234. 240.]
   [232. 231. 237.]
   [230. 229. 235.]
   ...
   [ 98.  97. 103.]
   [ 95.  94. 100.]
   [ 95.  94. 100.]]]


 [[[121. 125. 136.]
   [122. 126. 137.]
   [123. 127. 136.]
   ...
   [156. 158. 163.]
   [152. 157. 161.]
   [153. 158. 162.]]

  [[121. 125. 136.]
   [123. 127. 137.]
   [115. 120. 127.]
   ...
   [159. 160. 166.]
 

In [13]:
np.save("X.npy",X)
np.save("Y.npy",Y_age_gender)

In [14]:
img = Image.open('Dataset/' + files[98])
img = img.resize((64,64))
img.show()

In [15]:
img_array = np.array(img.resize((64,64)))
np.min(np.min(np.min(img_array)))

1

In [16]:
print(files[0])

100_0_0_20170112213500903.jpg.chip.jpg
